Repository schibsted/WAAS, pull requests merged in 2022-12, with the labels that each got.

#16 feat: add ability to see upload status in UI
  src/static/src/App.js
  src/static/src/components/UploadForm.js
  src/static/src/components/icons/Check.js
  src/static/src/components/icons/Update.js
  src/static/src/components/icons/index.js
  src/static/src/utils/uploadHandler.js
Labels: enhancement

#22 feat(static): add email input and advanced settings
  src/static/src/components/Settings.js
  src/static/src/styles/style.css
  src/static/src/utils/uploadHandler.js
Labels: enhancement

#19 feat: API use a worker
  .github/workflows/test.yaml
  .gitignore
  README.md
  docker-compose.yaml
  src/mailer.py
  src/main.py
  src/static/src/utils/uploadHandler.js
  src/transcriber.py
  src/worker.py
  tests/test_main.py
  upload-shared-tmp/.gitkeep
Labels: enhancement

#23 feat: add transcribe test
  .github/workflows/test.yaml
  src/main.py
  tests/test.mp3
  tests/test_main.py
Labels: enhancement

#25 fix: queue length API not working
  src/main.py
  tests/test_main.py
Labels: bug

#24 docs: env setup
  README.md
Labels: documentation

#28 Add credits and disclaimer
  README.md
  src/main.py
  src/static/src/components/UploadForm.js
  src/static/src/styles/style.css
  src/templates/index.html
Labels: enhancement

#31 fix: disclaimer inject html
  src/static/src/components/UploadForm.js
  src/templates/index.html
Labels: bug

#30 feat: html mailer
  src/__init__.py
  src/mailer.py
  src/main.py
  src/static/images/jojo-logo.png
  src/static/images/richard-horvath-RAZU_R66vUc-unsplash.jpg
  src/templates/success.html
  tests/test_main.py
Labels: enhancement

#34 feat: show queue status to user
  src/static/src/App.js
  src/static/src/components/Queue.js
  src/static/src/components/Settings.js
  src/static/src/components/UploadForm.js
  src/static/src/utils/getJobStatus.js
  src/static/src/utils/uploadHandler.js
Labels: enhancement

#35 feat: filename in subject and in transcription file
  README.md
  src/mailer.py
  src/main.py
  src/static/src/components/Queue.js
  src/static/src/utils/removeFileExtension.js
  src/static/src/utils/uploadHandler.js
  tests/test_main.py
Labels: enhancement

#36 feat: add filetype timecode txt in mail
  src/mailer.py
Labels: enhancement

#46 feat: save selected language to localstorage
  src/static/src/components/Settings.js
Labels: enhancement

#44 fix: color select menu windows
  src/static/src/styles/style.css
Labels: bug

#45 feat: remove clickable dropzone
  src/static/src/components/UploadForm.js
  src/static/src/styles/style.css
Labels: enhancement

#47 fix: backdrop filter safari
  src/static/src/styles/style.css
Labels: bug

#43 feat: settings with 2 steps
  src/static/src/components/SettingEmail.js
  src/static/src/components/SettingLanguage.js
  src/static/src/components/Settings.js
  src/static/src/styles/style.css
Labels: enhancement

#48 feat: change default font to system ui
  src/static/fonts/Inter/font-inter.css
  src/static/fonts/Inter/inter-v12-latin-500.woff2
  src/static/fonts/Inter/inter-v12-latin-600.woff2
  src/static/fonts/Inter/inter-v12-latin-800.woff2
  src/static/fonts/Inter/inter-v12-latin-regular.woff2
  src/static/src/styles/style.css
  src/templates/index.html
Labels: enhancement

#51 fix: remove margin bottom p upload form
  src/static/src/styles/style.css
Labels: enhancement

#50 fix: align file-name center
  src/static/src/styles/style.css
Labels: bug

#52 feat: move top languages to top
  src/static/src/components/Settings.js
Labels: enhancement

#53 fix: typo in settings broke api calls to option api
  src/static/src/components/Settings.js
Labels: bug

#54 feat: add queue position info
  src/static/src/components/Queue.js
  src/static/src/styles/style.css
  src/static/src/utils/pluralize.js
Labels: enhancement

#41 Adding sentry support
  docker-compose.yaml
  dotenv-example
  gunicorn.conf.py
  requirements.txt
  src/main.py
  src/worker.py
  worker-settings.py
Labels: enhancement

#57 feat: add sentry for frontend
  src/main.py
  src/templates/index.html
Labels: enhancement

#56 fix: utf-8 encode message and add from field in message
  src/mailer.py
Labels: bug, enhancement
