Repository schibsted/WAAS, pull requests merged in 2023-02, with the labels that each got.

#97 feat: clarify requirements to run the project
  README.md
Labels: documentation

#102 feat: setup security policy
  SECURITY.md
Labels: enhancement

#107 fix: cancel button settings form
  src/static/src/components/SettingEmail.js
Labels: bug

#108 feat: stats in docs
  README.md
Labels: documentation

#101 Offline editor of .jojo-files with audio playback
  src/static/src/App.js
  src/static/src/components/AudioPlayer.js
  src/static/src/components/Editor.js
  src/static/src/components/Table.js
  src/static/src/components/icons/PlayIcon.js
  src/static/src/components/icons/index.js
  src/static/src/styles/style.css
  src/static/src/utils/toTimeString.js
  src/static/src/utils/uploadHandler.js
Labels: enhancement
